### ISSUE TITLE
Channel Names

### ISSUE THREAD

**Issue by JoCouweleers** [jmwoloso/pychattr#4] opened 2019-08-30 23:29 UTC
Hi there, I am trying out pychattr with paths that may have up to 16 different channels. When the Markov model runs and I output the attribution model, the channel names don't appear to fully display but rather I only get what looks like the first letter of a channel. I also only see values for 6/16 channels. Do I have to make the channel touches into A > B > C as opposed to keeping the actual channel names? Thank you so much!

  channel_name  total_conversions
0            U      250737.490820
1            O      295364.685611
2            R      173576.549347
3            P       86361.447093
4            A       33434.827128
5            W           0.000000
6            G           0.000000

**Comment by jmwoloso** [comment] 2019-08-31 13:56
Well that's no good. Sorry about that. I'm out of town until Monday, but I'll take a look then and get back to you.

**Comment by jmwoloso** [comment] 2019-09-03 16:16
@JoCouweleers I started looking into this last night, but I'm still working through it. Thanks for your patience!

**Comment by JoCouweleers** [comment] 2019-09-03 16:18
Thank you so much! I played around a little and converted my initial
channel names to "A", "B", "C", etc. and that seemed to perform better.
Hope that helps! I'm very excited and grateful that you've created this
package!

**Comment by jmwoloso** [comment] 2019-09-04 03:08
@JoCouweleers Glad it is working for you in the interim, but that definitely isn't the desired behavior from my standpoint! 

I'll let you know when I have a fix, but for some backstory, for the initial porting over from R/C++ to python, I was translating things over literally so we'd at least have a baseline to build the library from. 

While the library itself is amazing, the variable names in the C++ code aren't that intuitive as far as what they do, so it'll take some manual debugging on my part. 

Obviously I missed something when coding it in python, but I'll get it fixed soon and let you know. In the mean time, you can create a dict to map your original channel names to single letter names.

Again, sorry for the inconveniences, but I'll get it fixed.

**Comment by SmilyPie1989** [comment] 2019-09-19 20:06
I've submitted a pull request to fix this. There was already a variable that could be used as the end position in a substring, but it wasn't being used. The end position variable is also one less than it should be. #5

**Comment by jmwoloso** [comment] 2019-09-28 01:47
@SmilyPie1989 Thanks! Sorry, was on vacation this past week. I'll take a look this weekend. Much appreciated!

**Comment by jmwoloso** [comment] 2019-10-16 15:34
Closing thanks to @SmilyPie1989's bug fix.

**Closed as completed by jmwoloso** 2019-10-16 15:34 UTC

**Comment by snehalnair** [comment] 2019-10-24 10:44
@jmwoloso I guess the issue is not resolved, it still returns first letter of a channel. I have about 700 channels. So I cant even rely on alphabets (26) or numbers (9). Please could you let me know a fix?

**Comment by jmwoloso** [comment] 2019-10-24 13:55
Hi @snehalnair. I will try and get a new release on pypi today, but in the mean time, if you build from master you should be fine.

700 channels is a ton! What field/domain are you analyzing?

**Comment by jmwoloso** [comment] 2019-10-25 01:46
@snehalnair I just published pychattr 0.2.1 on pypi, so you should just be able to `pip install -U pychattr` to get the changes that take care of the channel name issues.

**Comment by snehalnair** [comment] 2019-10-28 07:23
Hi @jmwoloso , thank you so much for such fast turn around. I will be running the models tomorrow,  will let you know how that goes. Thank you again!
